### ISSUE TITLE
是否能模拟低速网络？

### ISSUE THREAD

**Issue by fengmk2** [alibaba-archive/interceptor#3]
模拟速度慢的情况？

甚至一秒一字节？

**Comment by dead-horse** [comment]
应该可以按一样的原理模拟出来…发自我的 iPhone在 2012-11-17，23:38，fengmk2 notifications@github.com 写道：模拟速度慢的情况？

甚至一秒一字节？

```
          —
          Reply to this email directly or view it on GitHub.
```

**Comment by fengmk2** [comment]
感觉很过瘾，以前觉得做这样的东西蛮难的，现在都直接能做了。

**Comment by fengmk2** [comment]
这个我来做做看吧。

**Comment by aleafs** [comment]
从客户端来看，低速网和大延迟有啥区别？
